### ISSUE TITLE
wordpress_pets feeds are down

### ISSUE THREAD

**Issue by kevinchappell** [eclipsesource/tabris-js-template-app#10]
First off, I want to say Fantastic work. This is a great starter app to introduce developers to Tabris.js

At the time of writing this though [http://www.adoptapet.ie/](http://www.adoptapet.ie/) is down for maintenance which means so are their feeds. This breaks the `wordpress_pets` example. These things happen and it doesn't phase me but I wouldn't want to see other developers be dissuaded from using Tabris.js. Is it possible to swap this feed with another?

**Comment by gosia-eclipsesource** [comment]
@kevinchappell Thanks for your thoughtful comment! It looks like http://www.adoptapet.ie/ is back up so the WordPress example should be fine. @shaialon Can you confirm?

**Comment by kevinchappell** [comment]
Yup, it's up for me too but looks like their changes broke the feeds. Example [cats feed](http://www.adoptapet.ie/wp-json/posts?type=cats). I'll see if I can find replacement feeds and submit a pr.

**Comment by shaialon** [comment]
Thanks for the input @kevinchappell -  I will integrate a different Wordpress example.
Glad you found the starter useful!

**Comment by shaialon** [comment]
![autocomplete gif](https://cloud.githubusercontent.com/assets/3126207/15284526/7cf9fba8-1b5a-11e6-8d7a-f8b2b463a528.gif)
