### ISSUE TITLE
Exclamation mark menu entries do not work on Android

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js-template-app#7]
All entries lead to to the same error toast.
Observed on android.

![screenshot_2016-03-21-11-34-15](https://cloud.githubusercontent.com/assets/185295/13916557/9e020262-ef5b-11e5-9f1f-02bf80c954d1.png)

![screenshot_2016-03-21-11-34-19](https://cloud.githubusercontent.com/assets/185295/13916564/a2532134-ef5b-11e5-86a6-a6e6532b33a1.png)

**Comment by shaialon** [comment]
Resolved.
