### ISSUE TITLE
Exclamation mark icon duplicates "three dots" sharing icon

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js-template-app#8]
On Android only one of the two menu bar icons should be showing:
either the "three dots two lines" sharing icon or the exclamation mark icon.
IMHO they do the same thing.

**Comment by jonek** [comment]
![screenshot_2016-03-21-11-33-57](https://cloud.githubusercontent.com/assets/185295/13916664/4ea088dc-ef5c-11e5-8cc7-262efdbcf576.png)

**Comment by shaialon** [comment]
Resolved.
